use UNIVER
--create table TIMETABLE
--(
--TIMETABLEID INT PRIMARY KEY,
--ST_GROUP INT FOREIGN KEY REFERENCES
--ST_GROUP(IDGROUP),
--AUDIDORIUM NCHAR(20) FOREIGN KEY REFERENCES
--AUDITORIUM(AUDITORIUM),
--SUBJECT NCHAR(10) FOREIGN KEY REFERENCES
--SUBJECT(SUBJECT),
--TEACHER NCHAR(10) FOREIGN KEY REFERENCES
--TEACHER(TEACHER),
--DAY NVARCHAR(15),
--LESSON INT
--)
--INSERT INTO TIMETABLE
--VALUES 
--(1,22,N'301-1',N'ПЗ',N'НСКВ',N'Вторник',14.40),
--(2,25,N'304-4',N'СУБД',N'СМЛВ',N'Пятница',18.05),
--(3,23,N'320-4',N'ПСП',N'МХВ',N'Среда',16.30),
--(4,24,N'413-1',N'ПИС',N'МРЗВ',N'Понедельник',14.40),
--(5,27,N'313-1',N'ПЭХ',N'ЧРН',N'Вторник',14.40),
--(6,25,N'301-1',N'ПЭХ',N'ЧРН',N'Вторник',18.05),
--(7,26,N'324-1',N'ЭТ',N'КРЛВ',N'Среда',16.30);
SELECT AUDITORIUM.AUDITORIUM
FROM AUDITORIUM FULL OUTER JOIN TIMETABLE
ON AUDITORIUM.AUDITORIUM=TIMETABLE.AUDIDORIUM
WHERE TIMETABLE.LESSON IS NULL

