use UNIVER
select FACULTY.FACULTY, PULPIT.PULPIT_NAME
from FACULTY, PULPIT
Where FACULTY.FACULTY=PULPIT.FACULTY
select T1.PROFESSION, T2.FACULTY
FROM PROFESSION AS T1, FACULTY AS T2
WHERE T1.FACULTY=T2.FACULTY