USE ALBUMS
SELECT ARTISTS.ARTIST, ALBUMS.ALBUM_NAME
FROM ARTISTS FULL OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID

SELECT ARTISTS.ARTIST[ARTIST LEFT], ALBUMS.ALBUM_NAME[ALBUM LEFT]
FROM ARTISTS LEFT OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID

SELECT ARTISTS.ARTIST[ARTIST RIGHT], ALBUMS.ALBUM_NAME[ALBUM RIGHT]
FROM ARTISTS RIGHT OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID

SELECT ARTISTS.ARTIST, ALBUMS.ALBUM_NAME
FROM ARTISTS INNER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID

SELECT TRACK_LIST.TRACK_NAME, ARTISTS.ARTIST
FROM ARTISTS FULL OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID
FULL OUTER JOIN TRACK_LIST ON ALBUMS.ALBUMID=TRACK_LIST.ALBUMID 
WHERE TRACK_LIST.TRACK_NAME IS NOT NULL

SELECT TRACK_LIST.TRACK_NAME, ARTISTS.ARTIST
FROM ARTISTS FULL OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID
FULL OUTER JOIN TRACK_LIST ON ALBUMS.ALBUMID=TRACK_LIST.ALBUMID 
WHERE TRACK_LIST.ALBUMID IS NOT NULL

SELECT TRACK_LIST.TRACK_NAME, ARTISTS.ARTIST
FROM ARTISTS FULL OUTER JOIN ALBUMS
ON ARTISTS.ARTISTID=ALBUMS.ARTISTID
FULL OUTER JOIN TRACK_LIST ON ALBUMS.ALBUMID=TRACK_LIST.ALBUMID 
WHERE TRACK_LIST.TRACK_NAME IS NOT NULL AND TRACK_LIST.ALBUMID IS NOT NULL