USE ALBUMS;
--CREATE TABLE ARTISTS
--(
--ARTISTID nchar(10) not null PRIMARY KEY,  
--ARTIST NVARCHAR(100),
--NUMBER_OF_ALBUMS INT,
--NUMBER_OF_SONGS INT
--);
--CREATE TABLE ALBUMS
--(
--ALBUMID  INT identity(1,1) PRIMARY KEY,  
--ARTISTID nchar(10) foreign key references ARTISTS(ARTISTID),
--ALBUM_NAME NVARCHAR(100)
--);
--CREATE TABLE TRACK_LIST
--(
--TRACKID int primary key identity(1,1),
--ALBUMID INT foreign key references ALBUMS(ALBUMID),
--TRACK_NAME NVARCHAR(100)
--)
INSERT INTO ARTISTS
VALUES
('GHSTMN','GHOSTEMANE',5,63),
('MLNMTZ','MELANIE MARTINEZ',2,29),
('OOKRCK','ONE OK ROCK',3,41),
('HLS','HALSEY',2,32),
('KWNJNG','KWON JI YONG',4,26);
INSERT INTO ALBUMS(ARTISTID,ALBUM_NAME)
VALUES 
('GHSTMN', 'HEXADA'),
('GHSTMN', 'PLAGUES'),
('GHSTMN', 'ANTI-ICON'),
('GHSTMN', 'N/O/I/S/E'),
('GHSTMN', 'BLACKMAGE'),
('MLNMTZ', 'CRY BABY'),
('MLNMTZ', 'K-12'),
('OOKRCK', '35XXXV'),
('OOKRCK', 'ABITIONS'),
('OOKRCK', 'EYE OF THE STORM'),
('HLS', 'BADLANDS'),
('HLS', 'MANIC'),
('KWNJNG', 'KWON JI YONG'),
('KWNJNG', 'COUP D*ETAT'),
('KWNJNG', 'ONE OF THE KIND'),
('KWNJNG', 'HEARTBREAKER');
INSERT INTO TRACK_LIST(ALBUMID,TRACK_NAME)
VALUES
(3, 'AI'),
(3, 'FEDUP'),
(6, 'CRY BABY'),
(14, 'COUP DETAT'),
(13, 'SUPERSTAR'),
(10, 'GROW OLD DIE YOUNG');