USE master
CREATE DATABASE K_MyBase2
ON  PRIMARY 
( NAME = N'K_MyBase2_mdf', FILENAME = N'D:\Programs\SQL\MSSQL15.MSSQLSERVER2\MSSQL\DATA\K_MyBase2_mdf.mdf' , 
SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'K_MyBase2_ndf', FILENAME = N'D:\Programs\SQL\MSSQL15.MSSQLSERVER2\MSSQL\DATA\K_MyBase2_ndf.ndf' , 
SIZE = 8192KB , MAXSIZE = 1GB, FILEGROWTH = 10% ),
filegroup FG1
( NAME = N'K_MyBase2_fg1_1', FILENAME = N'D:\Programs\SQL\MSSQL15.MSSQLSERVER2\MSSQL\DATA\K_MyBase2_fgq-1.ndf' , 
SIZE = 8192KB , MAXSIZE = 1GB , FILEGROWTH = 25% ),
( NAME = N'K_MyBase2_fg1_2', FILENAME = N'D:\Programs\SQL\MSSQL15.MSSQLSERVER2\MSSQL\DATA\K_MyBase2_fgq-2.ndf' , 
SIZE = 8192KB , MAXSIZE = 1GB , FILEGROWTH = 25% )
 LOG ON 
( NAME = N'K_MyBase2_log', FILENAME = N'D:\Programs\SQL\MSSQL15.MSSQLSERVER2\MSSQL\DATA\K_MyBase2_log.ldf' , 
SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10% )
GO
