USE UNIVER
SELECT PULPIT.PULPIT_NAME
FROM PULPIT
WHERE PULPIT.FACULTY IN (SELECT FACULTY.FACULTY 
FROM FACULTY 
WHERE FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY 
FROM PROFESSION 
WHERE PROFESSION.PROFESSION_NAME LIKE N'%реумнкнц%'))

SELECT PULPIT.PULPIT_NAME
FROM PULPIT INNER JOIN FACULTY
ON PULPIT.FACULTY=FACULTY.FACULTY
WHERE FACULTY.FACULTY IN (SELECT PROFESSION.FACULTY 
FROM PROFESSION 
WHERE PROFESSION.PROFESSION_NAME LIKE N'%реумнкнц%')

SELECT PULPIT.PULPIT_NAME
FROM PULPIT INNER JOIN FACULTY
ON FACULTY.FACULTY=PULPIT.FACULTY
INNER JOIN PROFESSION 
ON FACULTY.FACULTY =PROFESSION.FACULTY
WHERE (PROFESSION_NAME LIKE N'%реумнкнц%')

-----------------4
SELECT AUDITORIUM_TYPE,AUDITORIUM_CAPACITY
FROM AUDITORIUM A
WHERE AUDITORIUM_CAPACITY=(SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM AA
WHERE AA.AUDITORIUM_TYPE=A.AUDITORIUM_TYPE ORDER BY AUDITORIUM_CAPACITY DESC)

-----------------5
SELECT FACULTY_NAME
FROM FACULTY 
WHERE NOT EXISTS (SELECT * FROM PULPIT
WHERE FACULTY.FACULTY=PULPIT.FACULTY)

-----------------6
SELECT TOP 1
(SELECT AVG(NOTE) FROM PROGRESS
WHERE PROGRESS.SUBJECT LIKE N'%ясад%') [ясад],
(SELECT AVG(NOTE) FROM PROGRESS
WHERE SUBJECT LIKE N'%ог%') [ог],
(SELECT AVG(NOTE) FROM PROGRESS
WHERE SUBJECT LIKE N'%щр%') [щр]
FROM PROGRESS

-----------------7

SELECT SUBJECT, NOTE 
FROM PROGRESS
WHERE NOTE >=ALL(SELECT NOTE FROM PROGRESS
WHERE SUBJECT LIKE N'%ясад%')

SELECT SUBJECT, NOTE 
FROM PROGRESS
WHERE NOTE >=ANY(SELECT NOTE FROM PROGRESS
WHERE SUBJECT LIKE N'%ясад%')

-----------------10
select NAME, BDAY, IDSTUDENT
from STUDENT as a
where BDAY in
(select BDAY from STUDENT as b 
where a.BDAY=b.BDAY and a.NAME!=b.NAME and a.IDSTUDENT!=b.IDSTUDENT);